---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  environment:
    ENVIRONMENT: 'production'
    TYPEORM_CONNECTION: 'postgres'
    TYPEORM_MIGRATIONS_DIR: './src/migrations'
    TYPEORM_ENTITIES: './src/modules/domain/**/*.entity.ts'
    TYPEORM_HOST: 'udacity.cbv7959kpsjz.us-east-1.rds.amazonaws.com'
    TYPEORM_PORT: '5432'
    TYPEORM_USERNAME: 'postgres'
    TYPEORM_PASSWORD: 'password'
    TYPEORM_DATABASE: 'glee'
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  roles:
    - deploy
