version: 2.1

orbs:
  slack: circleci/slack@4.3.0
  aws-cli: circleci/aws-cli@1.4.0

commands:
  notify-failure:
    description: Slack notification on failure
    steps:
      - slack/notify:
          event: fail
          custom: |
            {"blocks": [{"type": "section", "text": { "type": "mrkdwn", "text": "❌ $CIRCLE_JOB Failed in build #<$CIRCLE_BUILD_URL|$CIRCLE_BUILD_NUM> ($CIRCLE_BRANCH) of <https://$CIRCLE_REPOSITORY_URL|$CIRCLE_PROJECT_REPONAME>\n - $CIRCLE_USERNAME: $CIRCLE_TAG ($CIRCLE_SHA1)"}}]}
  notify-success:
    description: Slack notification on pass
    steps:
      - slack/notify:
          event: pass
          custom: |
            {"blocks": [{"type": "section", "text": { "type": "mrkdwn", "text": "✅ Build Succeded #<$CIRCLE_BUILD_URL|$CIRCLE_BUILD_NUM> ($CIRCLE_BRANCH) of <https://$CIRCLE_REPOSITORY_URL|$CIRCLE_PROJECT_REPONAME>\n - $CIRCLE_USERNAME: $CIRCLE_TAG ($CIRCLE_SHA1)"}}]}
  rollback:
    description: Delete Stacks
    steps:
      - aws-cli/default:
          event: fail
          custom: |
            aws cloudformation delete-stack --stack-name "uda-front-${CIRCLE_WORKFLOW_ID:0:7}"
            aws cloudformation delete-stack --stack-name "uda-back-${CIRCLE_WORKFLOW_ID:0:7}"

#  destroy-environment:
#    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
#    parameters:
#      # Add parameter here   
#    steps:
#      - run:
#          name: Destroy environments
#          when: on_fail
#          command: |
#            # Your code here
#            exit 1
#
#  revert-migrations:
#    description: Revert the last migration if successfully run in the current workflow.
#    parameters:
#      # Add parameter here     
#    steps:
#      - run:
#          name: Revert migrations
#          # Add when this will run
#          command: |
#            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
#            SUCCESS = 1
#            if(( $SUCCESS==1 )); 
#            then
#            #  cd ~/project/backend
#            #  npm install
#            #  Add revert code here. You can find this in the Getting Started section.
#              exit 1
#            fi
            
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-build-{{ checksum "/home/circleci/project/frontend/package-lock.json" }}
            - frontend-build-
      - run:
          name: Build front-end
          command: |
            cd frontend
            echo 'API_URL=http://localhost:3030' > .env
            npm install
            npm run build
      - notify-failure
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build-{{ checksum "/home/circleci/project/frontend/package-lock.json" }}

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - backend-build-{{ checksum "/home/circleci/project/backend/package-lock.json" }}
            - backend-build-
      - run:
          name: Back-end build
          command: |
             cd backend
             cp .env.sample .env
             npm install 
             npm run build
      - notify-failure
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build-{{ checksum "/home/circleci/project/backend/package-lock.json" }}

  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-build-{{ checksum "/home/circleci/project/frontend/package-lock.json" }}
            - frontend-build-
      - run:
          name: Run frontend unit tests
          command: |
             cd frontend
             npm run test
      - notify-failure
                
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - backend-build-{{ checksum "/home/circleci/project/backend/package-lock.json" }}
            - backend-build-
      - run:
          name: Run backend unit tests
          command: |
             cd backend
             npm run test
      - notify-failure
            
  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-build-{{ checksum "/home/circleci/project/frontend/package-lock.json" }}
            - frontend-build-
      - run:
          name: Run backend unit tests
          command: |
             cd backend
             npm install
             npm audit --audit-level=critical
      - notify-failure

  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - backend-build-{{ checksum "/home/circleci/project/backend/package-lock.json" }}
            - backend-build-
      - run:
          name: Run backend unit tests
          command: |
             cd backend
             npm install
             npm audit --audit-level=critical
      - notify-failure

  deploy-infrastructure:
    docker:
      - image: 'amazon/aws-cli'
    steps:
      - checkout
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --tags project=udapeople \
              --stack-name "uda-back-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
      - run:
          name: Ensure front-end infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --tags project=udapeople \
              --stack-name "uda-front-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            aws ec2 describe-instances --filters Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} --query 'Reservations[*].Instances[*].[PublicDnsName]' --output text >> .circleci/ansible/inventory.txt
            cat .circleci/ansible/inventory.txt | grep -oE "\bec2.+\b"
            cat .circleci/ansible/inventory.txt
      - run:
          name: Fix for tar and gzip utility are not present in this image but it is required. Please install it to have workflow workspace capability
          command: |
            yum install -y tar gzip
      - persist_to_workspace:
          root: ~/
          paths:
            - project/.circleci/ansible/inventory.txt
      - run:
          name: Delete front and back stacks if CF fails
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name "uda-front-${CIRCLE_WORKFLOW_ID:0:7}"
            aws cloudformation delete-stack --stack-name "uda-back-${CIRCLE_WORKFLOW_ID:0:7}"

  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["73:85:d9:b3:1c:c6:98:25:f5:f7:f7:b2:e2:81:92:b8"] 
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            cat .circleci/ansible/inventory.txt
            ansible-playbook -i .circleci/ansible/inventory.txt .circleci/ansible/configure-server.yml

  run-migrations:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Run migrations
          command: |
            cd backend
            npm install
            bash -c 'if npm run migrations | grep "has been executed successfully"; then MIGRATION=1; else MIGRATION=0; fi; curl -H "Content-Type: text/plain" -H "token: $MEMSTASH_TOKEN" --request PUT --data "$MIGRATION" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}'
      - run:
          name: Revert migrations
          when: on_fail
          command: |
            cd backend
            npm run migrations:revert

  deploy-frontend:
    docker:
      - image: cticti/aws-cli:node-alpine
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            cd frontend
            npm install
      - run:
          name: Get backend url
          command: |
            cd frontend
            export API_URL="http://$(cat .circleci/ansible/inventory.txt | grep -oE "\bec2.+\b"):3030"
            echo "${API_URL}"
            npm run build
      - run:
          name: Deploy frontend objects
          command: |
            bucketName="$(aws s3 ls | grep -oE "\udapeople-.+\b")"
            aws s3 cp ./frontend/dist s3://${bucketName}/ --recursive
            bucketName="$(aws s3 ls | grep -oE "\udapeople-${CIRCLE_WORKFLOW_ID:0:7}\b")"
      - run:
          name: Deploy frontend objects
          when: on_fail
          command: |
            aws s3 rm s3://${bucketName}/ --quiet --recursive   
                    
  deploy-backend:
    docker:
      - image: nikolaik/python-nodejs:python3.7-nodejs14-alpine
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["73:85:d9:b3:1c:c6:98:25:f5:f7:f7:b2:e2:81:92:b8"] 
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
            cd backend
            npm install 
            npm run build
            tar czf dist.tar.gz dist
      - run:
          name: Configure server
          command: |
            cat .circleci/ansible/inventory.txt
            ansible-playbook -i .circleci/ansible/inventory.txt .circleci/ansible/deploy-backend.yml

  smoke-test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Get backend url
          command: |
            BACKEND_URL="http://$(cat .circleci/ansible/inventory.txt | grep -oE "\bec2.+\b"):3030/api/status"
      - run:
          name: Backend smoke test.
          command: |
            curl ${BACKEND_URL}
      - run:
          name: Frontend smoke test.
          command: |
            export URL="http://udapeople-772ccf5.s3-website-us-east-1.amazonaws.com"
            if curl -s ${URL} | grep "Welcome"
            then
              exit 0
            else
              exit 1
            fi
      - run:
          name: Destroy environment ${CIRCLE_WORKFLOW_ID:0:7}
          when: on_fail
          command: |
            echo 'test'
      - run:
          name: Revert migrations
          when: on_fail
          command: |
            echo 'test'

##  cloudfront-update:
##    docker:
##      - image: 'amazon/aws-cli'
##    steps:
##      - checkout
##      - run:
##          name: Install dependencies
##          command: |
##            # your code here
##      - run:
##          name: Update cloudfront distribution
##          command: |
##            # your code here
##      # Here's where you will add some code to rollback on failure  
##
##cleanup:
##    docker:
##      # Docker image here
##    steps:
##      - checkout
##      - run:
##          name: Get old stack workflow id
##          command: |
##            # your code here
##            export OldWorkflowID="the id here"
##            export STACKS=[] #put the list of stacks here
##      - run:
##          name: Remove old stacks and files
##          command: |
##            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
##            then
##              # your code here
##            fi
##            

workflows:
  default:
    jobs:
##       - build-frontend
##       - build-backend
##       - test-frontend:
##           requires: [build-frontend]
##       - test-backend:
##           requires: [build-backend]
##       - scan-backend:
##           requires: [build-backend]
##       - scan-frontend:
##           requires: [build-frontend]
     - deploy-infrastructure:
#          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
          filters:
            branches:
              only: [master]
          context:
            - AWS
      - configure-infrastructure:
          requires: [deploy-infrastructure]
      - run-migrations:
          requires: [configure-infrastructure]
      - deploy-frontend:
          context:
            - AWS
          requires: [run-migrations]
      - deploy-backend:
          context:
            - AWS
          requires: [run-migrations]
##      - smoke-test:
##          requires: [deploy-backend, deploy-frontend]
##      - cloudfront-update:
##          requires: [smoke-test]
##      - cleanup:
##          requires: [cloudfront-update]